---
# tasks file for docker role

- name: Install Docker
  dnf:
    name: docker
    state: present
    update_cache: yes

- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: Create docker cli-plugins directory
  file:
    path: /usr/local/lib/docker/cli-plugins
    state: directory
    mode: '0755'

- name: Install docker-compose binary and plugin
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Symlink docker-compose to cli-plugins directory
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/local/lib/docker/cli-plugins/docker-compose
    state: link
    mode: 'a+x'
    force: false

- name: Install pip
  dnf:
    name: python3-pip
    state: present

- name: Update pip and install docker sdk for python
  pip:
    name: 
      - docker
    state: present
    extra_args: "--ignore-installed"
