# Auto-generated by Terraform — do not edit manually
# Run: terraform apply to regenerate

[lb]
${lb_public_ip} ansible_user=ubuntu ansible_ssh_private_key_file=${ssh_private_key_path}

[db]
${db_public_ip} ansible_user=ubuntu ansible_ssh_private_key_file=${ssh_private_key_path}

[all:vars]
db_private_ip=${db_private_ip}
efs_dns_name=${efs_dns_name}
cloudfront_domain=${cloudfront_domain}
s3_config_bucket=${s3_config_bucket}
project_name=${project_name}
db_name=${db_name}
db_user=${db_user}
db_password=${db_password}
db_root_password=${db_root_password}
lb_public_ip=${lb_public_ip}
asg_name=${asg_name}
aws_region=${aws_region}
